import type { OpeningLessonProfile } from "./types";

const family = "d4" as const;
function course(key: string, title: string, canonicalQuery: string, canonicalFallback: string | null, sideFocus: OpeningLessonProfile["sideFocus"], difficulty: OpeningLessonProfile["difficulty"], ecoRange: string, strategicPlan: string, opponentPlan: string, commonMistake: string, structureIdea: string, thematicBreak: string, keySquares: string[], tags: string[]): OpeningLessonProfile {
  return { key, slug: key, title, family, sideFocus, difficulty, ecoRange, canonicalQuery, canonicalFallback: canonicalFallback ?? undefined, summary: `${title} is taught through its recurring plan and structure: ${strategicPlan} ${structureIdea}`, strategicPlan, opponentPlan, commonMistake, trapWarning: `Tactical warning for ${title}: ${commonMistake} Check forcing replies before committing.`, structureIdea, thematicBreak, keySquares, tags };
}

export const D4_OPENING_PROFILES: OpeningLessonProfile[] = [
  course("queens-gambit","Queen's Gambit","Queen's Gambit",null,"white","beginner","D06-D69","Challenge d5 with c4, develop smoothly, and use queenside tension to gain central control.","Black decides whether to hold, return, or decline the c-pawn tension while activating the light bishop.","Releasing the tension too early can make Black's development easier and remove useful pressure on d5.","White's c4 pawn attacks the d5 anchor and creates long-term central and queenside pressure.","Prepare e4 when possible or exchange on d5 when it improves activity.",["c4","d5","e4"],["d4","queens-gambit","center"]),
  course("qga","Queen's Gambit Accepted","Queen's Gambit Accepted","Queen's Gambit","both","intermediate","D20-D29","Build a strong center after ...dxc4 and regain the pawn without wasting development tempi.","Black accepts c4 to deflect White's c-pawn, then returns material if needed to challenge the center.","Recovering c4 immediately at the cost of development misses the point of White's central freedom.","Black temporarily wins a wing pawn while White gains room for e4.","Use e4 to occupy the center before spending time on the c4 pawn.",["c4","e4","d5"],["qga","center","development"]),
  course("qgd","Queen's Gambit Declined","Queen's Gambit Declined","Queen's Gambit","both","beginner","D30-D69","Maintain pressure on d5 and understand when to exchange or build a minority attack.","Black supports d5 with e6 and seeks ...c5 or ...e5 to free the position.","Passive development can leave the c1 bishop trapped behind the e3 pawn chain.","The e6-d5 chain is solid but creates the classic problem of the c8 bishop.","Black aims for ...c5; White may exchange on d5 to create Carlsbad play.",["d5","c5","c8"],["qgd","positional","pawn-chain"]),
  course("qgd-orthodox","Queen's Gambit Declined: Orthodox Defense","Queen's Gambit Declined Orthodox","Queen's Gambit Declined","both","intermediate","D60-D69","Use classical development to increase pressure on d5 while keeping central options open.","Black develops solidly with ...Be7 and ...Nbd7 before seeking ...c5 or ...e5.","Exchanging every piece automatically can help the cramped side without improving White's position.","A compact black center trades space for durability and relies on timely liberation.","Prepare ...c5 or ...e5 only after enough pieces support the break.",["d5","c5","e5"],["qgd","orthodox","classical"]),
  course("qgd-exchange","Queen's Gambit Declined: Exchange Variation","Queen's Gambit Declined Exchange","Queen's Gambit Declined","white","intermediate","D35-D36","Use the Carlsbad structure for a minority attack or central e4 expansion based on piece placement.","Black counters with kingside activity, central breaks, or pressure on the c-file.","Pushing b4-b5 without support can create fixed weaknesses instead of targets.","White has a queenside pawn minority against Black's c- and d-pawns.","Use b4-b5 to create a c6 target, or prepare e4 when central expansion is stronger.",["b4","b5","c6"],["qgd","carlsbad","minority-attack"]),
  course("slav-defense","Slav Defense","Slav Defense",null,"black","beginner","D10-D19","Support d5 with ...c6 while keeping the light bishop free and flexible.","White increases pressure on d5 and tries to exploit slower queenside development.","Clinging to c4 for too long can cost several tempi and trap Black's queenside pieces.","Black's c6-d5 chain is solid and preserves the c8 bishop outside the pawn chain.","Use ...dxc4 or ...Bf5 at the right moment, then challenge the center later.",["c6","d5","f5"],["slav","solid","development"]),
  course("semi-slav-defense","Semi-Slav Defense","Semi-Slav Defense","Slav Defense","black","intermediate","D43-D49","Combine ...c6 and ...e6 for a resilient center and prepare dynamic ...e5 or ...c5 breaks.","White uses space and development to exploit the temporarily restricted c8 bishop.","A passive Semi-Slav without a freeing break becomes cramped quickly.","The c6-d5-e6 triangle is extremely solid but restricts the light bishop.","Use ...e5 as the thematic liberation when tactics and development permit.",["c6","d5","e5"],["semi-slav","dynamic","breaks"]),
  course("meran-variation","Semi-Slav Defense: Meran Variation","Semi-Slav Meran","Semi-Slav Defense","both","advanced","D47-D49","Understand ...dxc4 and ...b5 structures where Black gains queenside space but faces a dynamic center.","Black expands with ...b5, develops the bishop to b7, and prepares ...c5 or ...e5.","Trying to recover c4 too early can give Black easy development and queenside tempi.","Black's queenside chain gains space while central squares remain tactically sensitive.","Strike in the center with e4-e5 or meet ...c5 with active piece play.",["c4","b5","e5"],["semi-slav","meran","queenside"]),
  course("noteboom-variation","Semi-Slav Defense: Noteboom Variation","Noteboom Variation","Semi-Slav Defense","both","advanced","D31-D44","Balance Black's connected queenside passers against White's central space and activity.","Black protects and advances the queenside majority, aiming to make the passers a lasting asset.","Chasing the queenside pawns with pieces can neglect central development and king safety.","Black's advanced a- and b-pawns can become dangerous while White owns more central space.","Use e4 and central activity before the queenside passers become fully mobile.",["a4","b4","e4"],["semi-slav","noteboom","imbalance"]),
  course("london-system","London System","London System",null,"white","beginner","D00-D02","Develop Bf4 early, build a d4-e3-c3 shell, and attack only after pieces coordinate around e5.","Black challenges the center with ...c5, ...Qb6, or ...Bf5 and exploits predictable setup moves.","Playing the same setup mechanically can ignore direct pressure on b2, d4, or the light bishop.","The d4-e3-c3 triangle supports e5 and makes the early bishop development important.","Use e4 or e5 only when the center is prepared and counterplay is controlled.",["f4","e5","d4"],["london","system","beginner"]),
  course("jobava-london","Jobava London System","Jobava London","London System","white","intermediate","D00","Combine Nc3 and Bf4 for faster e4 and queenside tactical ideas than the traditional London.","Black challenges the center quickly and watches tactical motifs on b5, c7, and e5.","Launching Nb5 or e4 tactics without checking ...c5 can leave the center unstable.","Nc3 blocks the c-pawn but adds immediate pressure on d5 and supports e4.","Use e4 as the central expansion when the knight and bishop coordinate effectively.",["c3","e4","b5"],["london","jobava","tactical"]),
  course("colle-system","Colle System","Colle System",null,"white","beginner","D04-D05","Build a compact d4-e3-c3 center, complete development, then prepare the thematic e4 break.","Black uses space and active development to make e4 difficult and may expand on the queenside.","Continuing a fixed setup after Black has neutralized e4 can leave White without an active plan.","The Colle stores energy behind the e3 pawn until White can play e4.","Prepare e4 with Nbd2, Bd3, and castling before opening the center.",["e3","e4","d4"],["system","colle","center"]),
  course("stonewall-attack","Stonewall Attack","Stonewall Attack",null,"white","intermediate","D00","Use the d4-e3-f4 chain to control e5 and build kingside pressure with Ne5 and Bd3.","Black attacks the dark-square structure and tries to exchange the e5 knight.","Locking the light bishop behind the pawn chain without an escape route creates a bad piece.","White gains e5 control but weakens e4 and several light squares.","Use Ne5 as an outpost and organize kingside pressure after solving the light bishop.",["e5","f4","e4"],["stonewall","kingside","outpost"]),
  course("torre-attack","Torre Attack","Torre Attack",null,"white","beginner","A46-A48","Develop Bg5 before committing the c-pawn, then prepare e4 when the pin supports it.","Black challenges d4 and questions the bishop with ...Ne4, ...h6, or queenside pressure.","Saving the Bg5 bishop with repeated moves can lose more time than the bishop is worth.","White keeps the c-pawn flexible and uses the pin to support central expansion.","Prepare e4 as the main central break when pieces can support the advance.",["g5","e4","d4"],["torre","system","development"]),
  course("richter-veresov","Richter-Veresov Attack","Richter-Veresov Attack",null,"white","intermediate","D01-D05","Develop Nc3 and Bg5 to support e4 quickly and seek active piece play.","Black challenges the center with ...c5 or ...e5 and uses the blocked c-pawn as a target.","Forcing e4 when Black can immediately undermine it can turn space into overextension.","Nc3 increases central pressure but commits the c-pawn and makes activity essential.","Use e4 when development protects d4 and e4 from immediate counterattack.",["c3","e4","d4"],["veresov","active","center"]),
  course("blackmar-diemer","Blackmar-Diemer Gambit","Blackmar-Diemer Gambit",null,"white","advanced","D00-D01","Offer the e-pawn for rapid development, open files, and attacking chances.","Black consolidates the extra pawn, exchanges attackers, and returns material if needed.","If White fails to use the lead in development before simplification the pawn deficit remains.","White often trades a central pawn for open e- and f-files and quick minor-piece activity.","Use f3 and rapid castling to build pressure before Black completes development.",["f3","e4","f7"],["gambit","attack","advanced"]),
  course("chigorin-defense","Chigorin Defense","Chigorin Defense",null,"black","intermediate","D07","Use ...Nc6 to pressure d4 immediately and prioritize active piece play over c-pawn support.","White tries to exploit the knight's interference with ...c5 and maintain a stable center.","Defending d5 passively contradicts the active purpose of the knight development.","Black uses piece pressure rather than a traditional c-pawn chain to support d5.","Use ...e5 to challenge the center when tactical details allow it.",["c6","d4","e5"],["chigorin","active-defense","center"]),
  course("albin-countergambit","Albin Countergambit","Albin Countergambit",null,"black","advanced","D08-D09","Counter the Queen's Gambit with ...e5, using a d4 wedge and fast activity for the pawn.","White neutralizes the d4 pawn, develops, and avoids tactical traps before using the extra material.","Pushing the advanced d4 pawn without support can turn it from a cramping asset into a target.","Black's d4 pawn cramps White but may become overextended if the initiative disappears.","Use ...Bb4+ and piece activity to support the d4 wedge before White consolidates.",["e5","d4","b4"],["countergambit","tactical","advanced"]),
  course("tarrasch-defense","Tarrasch Defense","Tarrasch Defense",null,"black","intermediate","D32-D34","Use ...c5 to challenge the center actively, accepting an IQP for free piece play.","White blockades the isolated pawn, exchanges active pieces, and targets d5 later.","Defending the isolated pawn passively allows White to exploit the long-term weakness.","The IQP gives Black space and open lines but can become weak after exchanges.","Use activity around d4 and e4 before the position simplifies too far.",["d5","d4","e4"],["tarrasch","iqp","activity"]),
  course("semi-tarrasch","Semi-Tarrasch Defense","Semi-Tarrasch Defense","Queen's Gambit Declined","black","intermediate","D40-D42","Challenge d4 with ...c5 and use piece recaptures to keep active play without a fixed IQP.","White uses the central pawn majority and space to restrict Black before coordination is complete.","Exchanging into a passive position where White keeps the full center removes Black's dynamic justification.","Black trades central pawns to create piece activity rather than accepting a static weakness.","Use ...e5 or active pressure on d4 to contest White's central majority.",["c5","d4","e5"],["semi-tarrasch","active","center"]),
];
