import type { OpeningLessonProfile } from "./types";

const family = "e4" as const;
function course(key: string, title: string, canonicalQuery: string, canonicalFallback: string | null, sideFocus: OpeningLessonProfile["sideFocus"], difficulty: OpeningLessonProfile["difficulty"], ecoRange: string, strategicPlan: string, opponentPlan: string, commonMistake: string, structureIdea: string, thematicBreak: string, keySquares: string[], tags: string[]): OpeningLessonProfile {
  return { key, slug: key, title, family, sideFocus, difficulty, ecoRange, canonicalQuery, canonicalFallback: canonicalFallback ?? undefined, summary: `${title} is taught through its recurring plan and structure: ${strategicPlan} ${structureIdea}`, strategicPlan, opponentPlan, commonMistake, trapWarning: `Tactical warning for ${title}: ${commonMistake} Check forcing replies before committing.`, structureIdea, thematicBreak, keySquares, tags };
}

export const E4_OPENING_PROFILES: OpeningLessonProfile[] = [
  course("italian-game", "Italian Game", "Italian Game", null, "white", "beginner", "C50-C54", "Develop rapidly, castle early, and use c3-d4 or pressure on f7 when the center permits.", "Black seeks ...Nf6, ...Bc5 and a timely ...d5 break to neutralize the initiative.", "Launching an f7 attack before development is complete can leave White's king and center exposed.", "The e4/e5 center stays fluid until a d-pawn break opens files for the bishops.", "Prepare d4 only when enough pieces support the central expansion.", ["d4","e4","f7"], ["open-game","development","center"]),
  course("giuoco-piano", "Giuoco Piano", "Giuoco Piano", "Italian Game", "both", "beginner", "C50-C54", "Keep the center flexible, improve every minor piece, and choose the right moment for d4.", "The defender restrains d4 and looks for ...d5 after completing development.", "Slow wing pawn moves are costly even in a quiet center if pieces remain undeveloped.", "The e4/e5 center creates maneuvering play until c3-d4 or ...d5 changes the structure.", "Use c3 and d4 to challenge e5 once the king is secure.", ["d4","e4","e5"], ["quiet","maneuvering","center"]),
  course("evans-gambit", "Evans Gambit", "Evans Gambit", "Italian Game", "white", "intermediate", "C51-C52", "Use b4 to gain tempi on the bishop, then build c3-d4 and accelerate every piece toward the center.", "Black should return material when useful and finish development before the initiative becomes dangerous.", "Continuing to sacrifice after the initiative has faded leaves White simply down material.", "A wing pawn is traded for a broad central pawn mass and open attacking lines.", "Drive the bishop away with b4, then establish c3-d4 while development has momentum.", ["b4","d4","f7"], ["gambit","tactical","initiative"]),
  course("two-knights-defense", "Two Knights Defense", "Two Knights Defense", "Italian Game", "both", "intermediate", "C55-C59", "Treat ...Nf6 as a tactical challenge to e4 and calculate Ng5 ideas without neglecting development.", "Black counters in the center, especially with ...d5, rather than defending f7 passively.", "Repeated pawn or piece grabs with one attacker can lose the lead in development.", "The center is fluid because e4 and f7 are both tactical targets from the first moves.", "Use central counterplay such as ...d5 to challenge a premature kingside attack.", ["e4","f7","d5"], ["tactical","open-game","calculation"]),
  course("ruy-lopez", "Ruy Lopez", "Ruy Lopez", null, "white", "beginner", "C60-C99", "Pressure e5 with Bb5, preserve tension, and prepare c3-d4 while developing naturally.", "Black challenges the bishop, reinforces e5, and seeks ...d5 or queenside counterplay.", "Exchanging on c6 automatically can surrender the bishop pair without gaining a useful structural target.", "The e4/e5 center stays tense while c3-d4 and ...d5 are the main liberating breaks.", "Prepare c3 and d4 to challenge the e5 anchor without releasing tension too early.", ["d4","e5","c6"], ["positional","pressure","open-game"]),
  course("ruy-lopez-berlin", "Ruy Lopez: Berlin Defense", "Ruy Lopez Berlin Defense", "Ruy Lopez", "both", "intermediate", "C65-C67", "Value activity, king centralization, and the bishop pair when the Berlin leads to early queen trades.", "Black attacks e4 immediately and aims for durable activity rather than a direct kingside battle.", "Treating the queenless middlegame as automatically drawn often leads to passive pieces and bad endgames.", "The Berlin can produce doubled c-pawns, an active central king, and a long fight over e5.", "Improve piece activity before committing pawn breaks in the simplified structure.", ["e5","d5","c6"], ["endgame","berlin","positional"]),
  course("ruy-lopez-exchange", "Ruy Lopez: Exchange Variation", "Ruy Lopez Exchange", "Ruy Lopez", "white", "intermediate", "C68-C69", "Exchange on c6 to damage Black's queenside and target the long-term pawn majority.", "Black relies on the bishop pair and active pieces to compensate for doubled queenside pawns.", "Assuming doubled pawns are weak by themselves can allow Black to gain enough activity to equalize.", "White plays against doubled c-pawns while Black values open lines and two bishops.", "Simplify only when the healthier pawn majority matters more than Black's activity.", ["c6","e5","d4"], ["endgame","structure","bishop-pair"]),
  course("scotch-game", "Scotch Game", "Scotch Game", null, "white", "beginner", "C44-C45", "Open the center with d4 immediately and use active development instead of preserving a closed pawn chain.", "Black contests d4 and targets exposed white pieces with developing moves.", "Early queen adventures can give Black free development while both kings remain in the center.", "Central exchanges clear files and make development speed more important than extra space.", "Use d4 to open lines before Black settles into a comfortable e5 structure.", ["d4","e4","e5"], ["open-center","development","tactical"]),
  course("scotch-gambit", "Scotch Gambit", "Scotch Gambit", "Scotch Game", "white", "intermediate", "C44-C45", "Offer the d-pawn for rapid development and open lines toward f7 while Black's king is uncastled.", "Black tries to consolidate or return material to complete development and blunt the initiative.", "An open center is not compensation if White's own pieces remain undeveloped.", "Open diagonals for Bc4 and central files give White activity in exchange for material or structure.", "Use c3 or Re1 to support development before forcing tactics on f7.", ["f7","d4","e5"], ["gambit","initiative","open-center"]),
  course("vienna-game", "Vienna Game", "Vienna Game", null, "white", "beginner", "C25-C29", "Develop Nc3 before Nf3 to keep f-pawn ideas available while pressuring e5 and d5.", "Black strikes at the center with ...Nf6 and ...d5 before White's flexible setup becomes an attack.", "Pushing f4 without accounting for king safety can create more weaknesses than initiative.", "The e4 pawn and flexible f-pawn create kingside space while leaving central counterplay available.", "Choose f4 only when development supports it, otherwise keep pressure on e5 and d5.", ["f4","e5","d5"], ["flexible","kingside","center"]),
  course("vienna-gambit", "Vienna Gambit", "Vienna Gambit", "Vienna Game", "white", "intermediate", "C25-C29", "Use f4 to challenge e5 and open the f-file, but ground the attack in development and central control.", "Black answers with central counterplay instead of accepting a passive kingside defense.", "Automatic recaptures on f4 can miss the fact that open lines favor the better-developed side.", "The f-pawn advance creates an asymmetrical center and weakens squares around both kings.", "Challenge e5 with f4, then bring Nf3 and Bc4 into the attack.", ["f4","e5","f7"], ["gambit","kingside","initiative"]),
  course("kings-gambit", "King's Gambit", "King's Gambit", null, "white", "intermediate", "C30-C39", "Offer the f-pawn to deflect e5, build a broad center, and open the f-file for rapid activity.", "Black keeps the extra pawn only when it can be defended without falling behind in development.", "Spending several tempi recovering the gambit pawn destroys the time-based compensation.", "The open f-file creates attacking chances but also weakens White's own king.", "Use d4 and Nf3 to dominate the center while the f-file becomes an attacking lane.", ["f4","e5","f7"], ["gambit","tactical","king-safety"]),
  course("bishops-opening", "Bishop's Opening", "Bishop's Opening", null, "white", "beginner", "C23-C24", "Develop Bc4 early while keeping options for f4, d3, and transpositions into Italian or Vienna structures.", "Black uses ...Nf6 or ...c6-d5 to challenge the center and reduce pressure on f7.", "Preserving the c4 bishop at any cost can waste tempi if the center closes and the bishop loses scope.", "The structure stays flexible until White chooses d3, d4, or f4.", "Choose d4 for central play or f4 for kingside space based on Black's setup.", ["c4","f7","d4"], ["flexible","development","open-game"]),
  course("four-knights-game", "Four Knights Game", "Four Knights Game", null, "both", "beginner", "C47-C49", "Complete natural development and then create imbalance with d4, Bb5, or a central exchange.", "Black mirrors only while useful and looks for ...Bb4 or ...d5 to break symmetry.", "Copying moves mechanically can surrender the initiative once one side gets the first central break.", "A symmetrical e4/e5 center leaves activity to the side that times d4 or ...d5 best.", "Use d4 or ...d5 to turn equal development into active central play.", ["d4","d5","e5"], ["symmetrical","development","center"]),
  course("ponziani-opening", "Ponziani Opening", "Ponziani Opening", null, "white", "intermediate", "C44", "Support d4 with c3 and aim for a large center, accepting that the c-pawn delays normal knight development.", "Black attacks the center immediately with ...d5 or ...Nf6 before White consolidates.", "Defending e4 passively wastes the point of c3, which must lead to central space.", "White invests a tempo in c3 to prepare d4 but temporarily blocks Nb1.", "Play d4 decisively once c3 has prepared it, while watching Black's central counterstrike.", ["c3","d4","e4"], ["center","space","development"]),
  course("petrovs-defense", "Petrov's Defense", "Petrov Defense", null, "both", "intermediate", "C42-C43", "Understand the tactical symmetry after ...Nf6, centralize pieces, and avoid rote pawn grabbing.", "Black counterattacks e4 rather than defending e5 and seeks active equality.", "Imitating captures blindly can leave a knight stranded or a king exposed because move order matters.", "Early exchanges often create symmetry where active piece placement matters more than structure.", "Use d4 or ...d5 once the tactical e-pawn sequence is resolved.", ["e4","e5","d4"], ["symmetrical","tactical","precision"]),
  course("philidor-defense", "Philidor Defense", "Philidor Defense", null, "white", "beginner", "C41", "Use the space advantage from d4 and prevent Black from freeing the cramped center with ...d5.", "Black supports e5 with ...d6 and later seeks ...f5 or ...d5.", "Overextending with pawn pushes can give Black the exact central break needed to activate the pieces.", "Black's e5-d6 chain is solid but restricts the dark bishop until a break occurs.", "Maintain d4 pressure and make ...d5 difficult before starting wing play.", ["d4","e5","d6"], ["space","closed-center","breaks"]),
  course("center-game", "Center Game", "Center Game", null, "white", "beginner", "C21-C22", "Open the center with d4 and justify early queen activity through fast development and tempo-conscious play.", "Black develops with tempo against the exposed queen and contests the open center.", "Moving the queen repeatedly after an early recapture can hand Black a free lead in development.", "The center opens immediately, so every queen move must be justified by concrete activity.", "Use open files and fast development to compensate for early queen exposure.", ["d4","e4","e5"], ["open-center","tempo","development"]),
  course("danish-gambit", "Danish Gambit", "Danish Gambit", "Center Game", "white", "intermediate", "C21", "Offer queenside pawns to accelerate both bishops and create direct pressure on the center and f7.", "Black returns material if needed to finish development and extinguish the initiative.", "Continuing to sacrifice after Black has consolidated leaves White without enough compensation.", "White trades queenside pawns for open diagonals on b2 and c1 and rapid piece activity.", "Coordinate Bc4 and Bb2 on long diagonals before forcing tactical operations.", ["b2","c4","f7"], ["gambit","development","bishops"]),
  course("elephant-gambit", "Elephant Gambit", "Elephant Gambit", null, "black", "advanced", "C40", "Use the early ...d5 pawn offer to challenge e4 and create immediate central tactics for activity.", "White should exploit the material edge by developing rather than entering unnecessary complications.", "A pawn sacrifice is not compensation if Black remains undeveloped and the center simply opens against the king.", "The early ...d5 break destabilizes e4/e5 but can leave Black with structural weaknesses if the initiative fades.", "Open the center only when the resulting tempi activate pieces faster than the material deficit hurts.", ["d5","e4","e5"], ["gambit","counterattack","advanced"]),
];
