import type { OpeningLessonProfile } from "./types";

const family = "flank-and-systems" as const;
function course(key: string, title: string, canonicalQuery: string, canonicalFallback: string | null, sideFocus: OpeningLessonProfile["sideFocus"], difficulty: OpeningLessonProfile["difficulty"], ecoRange: string, strategicPlan: string, opponentPlan: string, commonMistake: string, structureIdea: string, thematicBreak: string, keySquares: string[], tags: string[]): OpeningLessonProfile {
  return { key, slug: key, title, family, sideFocus, difficulty, ecoRange, canonicalQuery, canonicalFallback: canonicalFallback ?? undefined, summary: `${title} is taught through its recurring plan and structure: ${strategicPlan} ${structureIdea}`, strategicPlan, opponentPlan, commonMistake, trapWarning: `Tactical warning for ${title}: ${commonMistake} Check forcing replies before committing.`, structureIdea, thematicBreak, keySquares, tags };
}

export const FLANK_SYSTEM_PROFILES: OpeningLessonProfile[] = [
  course("english-opening","English Opening","English Opening",null,"white","beginner","A10-A39","Control d5 from the flank with c4, keep the center flexible, and choose the right transposition.","Black can mirror with ...c5, occupy the center with ...e5, or challenge with ...d5 structures.","Flank moves without a central plan can leave White with space but no pressure.","The c-pawn gains queenside room and controls d5 while the d-pawn remains flexible.","Use d4 when central occupation is favorable, or b4 for queenside expansion in suitable structures.",["c4","d5","d4"],["english","flank","flexible"]),
  course("english-symmetrical","English Opening: Symmetrical Variation","English Symmetrical","English Opening","both","intermediate","A30-A39","Break the mirror with d4, b4, or asymmetric piece placement rather than copying indefinitely.","Black mirrors only while it preserves flexibility and then chooses a useful break.","Assuming equal pawn placement means equal plans can surrender the initiative.","Both sides advance c-pawns, making d4/d5 and queenside expansion central themes.","Use d4 or ...d5 to create asymmetry when development supports it.",["c4","c5","d4"],["english","symmetrical","breaks"]),
  course("english-four-knights","English Opening: Four Knights Variation","English Four Knights","English Opening","both","intermediate","A28-A29","Develop both knights while keeping d4 flexible, then choose g3, d4, or queenside expansion.","Black uses active piece placement and central pressure to deny effortless d5 control.","Drifting into symmetry without preparing a pawn break leaves both sides with no clear plan.","Natural development creates a flexible center where one d-pawn break changes the structure.","Use d4 once your pieces support the resulting exchanges.",["d4","d5","c4"],["english","development","flexible"]),
  course("english-botvinnik","English Opening: Botvinnik System","English Botvinnik","English Opening","white","advanced","A25-A29","Build a c4-e4 dark-square bind and maneuver behind the space before choosing f4 or b4.","Black attacks the fixed dark squares with ...c6-d5 or queenside pressure.","Locking the center without controlling d4 can hand Black a permanent outpost.","White's c4-e4 chain controls d5 while conceding d4 as a strategic square.","Use f4 for kingside space or b4 for queenside play after securing d4.",["c4","e4","d4"],["english","botvinnik","bind"]),
  course("reti-opening","Réti Opening","Reti Opening",null,"white","beginner","A04-A09","Invite Black to occupy the center, then attack it with c4, g3, and piece pressure.","Black uses extra central space but must defend it against flank pressure and timely breaks.","Hypermodern play becomes passivity if White never challenges the center.","White often fianchettos and keeps d-pawn options open while targeting d5 and e5.","Use c4 or d4 when the central tension favors White's development.",["c4","d5","e5"],["reti","hypermodern","flexible"]),
  course("reti-gambit","Réti Gambit","Reti Gambit","Reti Opening","white","intermediate","A09","Use an early pawn offer to accelerate development and undermine Black's central chain.","Black should keep material only when the center and development remain secure.","Chasing sacrificed material back with repeated pawn moves wastes the open lines created by the gambit.","The gambit challenges central pawns from the flank and opens files for rapid development.","Strike at d5 or e5 before Black consolidates the extra material.",["c4","d5","e5"],["reti","gambit","initiative"]),
  course("kings-indian-attack","King's Indian Attack","King's Indian Attack",null,"white","beginner","A05-A08","Use Nf3-g3-Bg2-d3-e4 as a flexible shell, then prepare e5 and kingside pressure.","Black gains central or queenside space and tries to open the center before White's attack develops.","Attacking automatically when the center is open can expose White's own king and pieces.","The e4-d3 chain and fianchetto support e5 and kingside maneuvering.","Use e5 to gain space and transfer pieces toward the king when the center supports it.",["e4","e5","g2"],["kia","system","kingside"]),
  course("catalan-opening","Catalan Opening","Catalan Opening",null,"white","intermediate","E00-E09","Combine Queen's Gambit pressure with a g2 fianchetto and long-diagonal queenside pressure.","Black decides whether to hold c4, return it, or build a closed center while neutralizing Bg2.","Assuming the g2 bishop is strong without opening its diagonal can leave White with a decorative piece.","White's c4-d4 center plus Bg2 creates long-term pressure on b7 and the queenside.","Use cxd5 or e4 to open lines for the bishop when the timing is right.",["g2","b7","d5"],["catalan","fianchetto","positional"]),
  course("bird-opening","Bird Opening","Bird Opening",null,"white","intermediate","A02-A03","Use f4 to control e5 and build a reversed Dutch setup while respecting king-safety weaknesses.","Black attacks the e1-h4 diagonal and challenges the center before White's space matters.","Playing f4 without a plan for king safety can create more weaknesses than activity.","The f-pawn controls e5 but weakens e3 and the king's diagonal.","Use e4 when prepared for a broad center, or e3 for a more restrained setup.",["f4","e5","e3"],["bird","flank","kingside"]),
  course("dutch-defense","Dutch Defense","Dutch Defense",null,"black","beginner","A80-A99","Use ...f5 to control e4 and create kingside ambitions, accepting a committal structure.","White challenges the dark squares and center with g3, Bg2, and pressure on e4/e6.","Starting a kingside attack before development is complete compounds the weaknesses created by ...f5.","Black's f5 pawn gains e4 control but weakens e6 and king-side diagonals.","Use ...e5 when possible to seize the center, or ...c5 for queenside counterplay.",["f5","e4","e5"],["dutch","aggressive","center"]),
  course("dutch-leningrad","Dutch Defense: Leningrad Variation","Dutch Leningrad","Dutch Defense","black","advanced","A87-A89","Fianchetto behind ...f5 and combine kingside space with the central ...e5 break.","White targets e6 and dark squares while trying to open the center before Black attacks.","Playing ...e5 before development supports it can expose the king and d5 square.","The g7 bishop and f5 pawn create dynamic pressure with a flexible center.","Prepare ...e5 with ...d6 and coordinated pieces.",["g7","f5","e5"],["dutch","leningrad","fianchetto"]),
  course("dutch-stonewall","Dutch Defense: Stonewall Variation","Dutch Stonewall","Dutch Defense","black","intermediate","A90-A95","Build the f5-e6-d5-c6 chain, control e4, and establish a knight on e4.","White attacks e5 and the light-square weaknesses while trying to exchange the e4 knight.","Locking the light bishop behind the chain without a route to activity creates a long-term bad piece.","The Stonewall gives a strong e4 outpost but leaves e5 and light squares sensitive.","Use ...Ne4 as the anchor before organizing kingside pressure.",["e4","e5","f5"],["dutch","stonewall","outpost"]),
  course("dutch-classical","Dutch Defense: Classical Variation","Dutch Classical","Dutch Defense","black","intermediate","A84-A99","Develop naturally with ...Nf6, ...e6, ...Be7 and castle before choosing ...e5.","White pressures e6 and dark squares while using the central space advantage.","Premature kingside pawn pushes can expose Black before the pieces coordinate.","Black keeps a flexible f5-e6 structure and delays the exact central break.","Prepare ...e5 only once the king is safe and the center cannot punish it.",["f5","e6","e5"],["dutch","classical","flexible"]),
  course("nimzo-larsen-attack","Nimzo-Larsen Attack","Nimzo-Larsen Attack",null,"white","intermediate","A01","Fianchetto the queen bishop with b3-Bb2, pressure e5, and keep central pawns flexible.","Black occupies the center and tries to blunt the b2 bishop with a stable chain.","Pure flank play can allow Black to build a center that is too stable to challenge later.","The b2 bishop attacks the center from long range while White delays direct occupation.","Use f4, e4, or c4 to challenge the center once development is ready.",["b2","e5","c4"],["nimzo-larsen","fianchetto","hypermodern"]),
  course("polish-opening","Polish Opening","Polish Opening",null,"white","intermediate","A00","Use b4 for queenside space and Bb2, but connect the flank expansion to central pressure.","Black attacks the advanced b-pawn and occupies the center while White spends time on the wing.","Defending b4 with more pawn moves can create a serious development deficit.","White gains queenside space and opens b2 at the cost of immediate central influence.","Use Bb2 and c4/e3 to challenge the center rather than expanding blindly.",["b4","b2","c4"],["polish","flank","queenside"]),
  course("grob-opening","Grob Opening","Grob Opening",null,"white","advanced","A00","Use g4 as a surprise weapon for kingside space while accepting serious king-safety risk.","Black attacks g4 and centralizes rapidly to exploit the weakened kingside.","Continuing to push kingside pawns while development lags can make White's king the main target.","The g-pawn advance weakens f3/h3 while creating unusual long-diagonal pressure.","Challenge the center quickly so the flank pawn investment produces active piece play.",["g4","f3","e4"],["grob","unorthodox","advanced"]),
  course("van-geet-opening","Van Geet Opening","Van Geet Opening",null,"white","intermediate","A00","Develop Nc3 first, keep e4/d4 flexible, and use transpositions to avoid early commitment.","Black can occupy the center and force White to show how the knight supports a coherent plan.","Blocking the c-pawn with Nc3 is only justified if the knight creates real central pressure.","The early knight supports e4 and d5 but reduces c-pawn flexibility.","Use e4 or d4 according to Black's central setup and the role of Nc3.",["c3","e4","d5"],["van-geet","flexible","development"]),
  course("zukertort-opening","Zukertort Opening","Zukertort Opening",null,"white","beginner","A04-A09","Start Nf3 to control e5 while preserving every central pawn option.","Black uses the freedom to claim space and tries to force White into a passive response.","Flexibility has no value if White never turns it into an active central challenge.","White delays pawn commitments and decides later between c4, d4, and g3 structures.","Choose c4 or d4 once Black's center reveals the best target.",["f3","e5","d4"],["zukertort","flexible","transposition"]),
  course("kings-fianchetto","King's Fianchetto Opening","King's Fianchetto Opening",null,"white","beginner","A00","Prepare Bg2 with g3, control the long diagonal, and choose a center that gives the bishop targets.","Black occupies the center and may try to close the g2 bishop with a stable pawn chain.","Fianchettoing and then ignoring the center leaves the bishop without meaningful influence.","The g2 bishop exerts long-range pressure while White keeps central pawns flexible.","Use c4 or e4 to attack the center and open lines for Bg2.",["g2","c4","e4"],["fianchetto","system","beginner"]),
  course("sodium-attack","Sodium Attack","Sodium Attack",null,"white","advanced","A00","Use Na3 as an offbeat development choice while preserving c-pawn flexibility and aiming the knight toward c4 or b5.","Black should occupy the center quickly and make the edge knight justify its route back toward useful squares.","Leaving the a3 knight disconnected from central play gives Black a free space advantage.","The unusual knight placement preserves the c-pawn but spends time reaching central influence.","Re-route the knight toward c4 or b5 while challenging the center with c4 or e4.",["a3","c4","b5"],["sodium","unorthodox","development"]),
];
