import type { OpeningLessonProfile } from "./types";

const family = "indian-defenses" as const;
function course(key: string, title: string, canonicalQuery: string, canonicalFallback: string | null, sideFocus: OpeningLessonProfile["sideFocus"], difficulty: OpeningLessonProfile["difficulty"], ecoRange: string, strategicPlan: string, opponentPlan: string, commonMistake: string, structureIdea: string, thematicBreak: string, keySquares: string[], tags: string[]): OpeningLessonProfile {
  return { key, slug: key, title, family, sideFocus, difficulty, ecoRange, canonicalQuery, canonicalFallback: canonicalFallback ?? undefined, summary: `${title} is taught through its recurring plan and structure: ${strategicPlan} ${structureIdea}`, strategicPlan, opponentPlan, commonMistake, trapWarning: `Tactical warning for ${title}: ${commonMistake} Check forcing replies before committing.`, structureIdea, thematicBreak, keySquares, tags };
}

export const INDIAN_DEFENSE_PROFILES: OpeningLessonProfile[] = [
  course("kings-indian-defense","King's Indian Defense","King's Indian Defense",null,"black","beginner","E60-E99","Allow White to occupy the center, fianchetto, then attack the pawn chain with ...e5 or ...c5.","White uses space for queenside expansion or central pressure while watching the kingside attack.","Sitting behind the center without a pawn break turns hypermodern pressure into simple passivity.","White often owns more central space while Black's g7 bishop and breaks create dynamic pressure.","Choose ...e5 for a closed center or ...c5 for direct pressure on d4.",["e5","c5","d4"],["kings-indian","hypermodern","counterplay"]),
  course("kid-classical","King's Indian Defense: Classical Variation","King's Indian Classical","King's Indian Defense","both","intermediate","E90-E99","Understand the closed-center race: White expands queenside while Black prepares ...f5 against the king.","White uses c5 and queenside space to attack the base of Black's structure.","Starting a kingside pawn storm before the center is fixed can expose Black's own king.","The e4-d5 versus e5-d6 chains point attacks toward opposite wings.","Use ...f5 to attack White's e4 chain once the center is closed.",["f5","e4","d5"],["kings-indian","classical","opposite-wings"]),
  course("kid-samisch","King's Indian Defense: Sämisch Variation","King's Indian Samisch","King's Indian Defense","white","advanced","E80-E89","Build a broad center with f3 and choose a coherent king-safety and pawn-expansion plan.","Black attacks the center with ...e5 or ...c5 and targets White's slower development.","Pushing kingside pawns before deciding where the king belongs can create lasting weaknesses.","White's f3-e4-d4 chain gives strong control but commits time and dark squares.","Use g4 or d5 only when development supports the chosen attacking plan.",["f3","e4","d5"],["kings-indian","samisch","space"]),
  course("kid-four-pawns","King's Indian Defense: Four Pawns Attack","King's Indian Four Pawns Attack","King's Indian Defense","white","advanced","E76-E79","Use the massive center to gain space and force Black to prove the hypermodern setup quickly.","Black attacks the pawn chain with ...c5, ...e5, and tactical pressure before White completes development.","Advancing every central pawn without piece support can make the center collapse under attack.","White's c4-d4-e4-f4 pawns dominate space but also create multiple targets.","Choose d5 or e5 only when the advance gains lasting space and keeps the center connected.",["c4","d4","f4"],["kings-indian","four-pawns","space"]),
  course("kid-fianchetto","King's Indian Defense: Fianchetto Variation","King's Indian Fianchetto","King's Indian Defense","white","intermediate","E60-E69","Fianchetto the king bishop to reinforce the center and reduce the force of Black's standard kingside attack.","Black shifts toward central and queenside counterplay because the white king is harder to attack directly.","A quiet fianchetto setup still needs active central or queenside play to use the space advantage.","Both sides often use long diagonals while the center stays strategically tense.","Use d5 or queenside expansion to restrict Black's central breaks.",["g2","d5","c5"],["kings-indian","fianchetto","positional"]),
  course("nimzo-indian-defense","Nimzo-Indian Defense","Nimzo-Indian Defense",null,"black","beginner","E20-E59","Pin Nc3 with ...Bb4 to control e4 and use rapid development to pressure White's center.","White uses the bishop pair, central space, or queenside pawns as compensation for structural concessions.","Giving up the dark bishop automatically can surrender a valuable piece without gaining a useful structure.","Doubled c-pawns, bishop-pair compensation, and control of e4 define many Nimzo structures.","Use ...d5 or ...c5 after deciding how to handle the c3 knight.",["c3","e4","c5"],["nimzo","pin","structure"]),
  course("nimzo-rubinstein","Nimzo-Indian Defense: Rubinstein Variation","Nimzo Indian Rubinstein","Nimzo-Indian Defense","white","intermediate","E40-E59","Use e3 for solid development and exploit the bishop pair without allowing easy pressure on c4 or d4.","Black attacks the center and may create structural targets with ...d5, ...c5, or ...Bxc3.","A passive setup gives Black easy equality before the bishop pair becomes relevant.","White stays flexible until the c3 exchange or central break clarifies the pawn skeleton.","Prepare e4 or d5 expansion only after development is complete.",["e3","e4","c3"],["nimzo","rubinstein","bishop-pair"]),
  course("nimzo-classical","Nimzo-Indian Defense: Classical Variation","Nimzo Indian Classical","Nimzo-Indian Defense","white","advanced","E32-E39","Use Qc2 to protect c3 and support e4 while keeping the option to recapture with the queen.","Black develops with tempo and tries to exploit the queen's early placement.","Protecting the bishop pair at the cost of several tempi can let Black seize the center.","Qc2 preserves structure but makes queenside development less natural.","Use e4 only when queen, knight, and pawns support the expansion tactically.",["c2","e4","c3"],["nimzo","classical","queen-development"]),
  course("nimzo-samisch","Nimzo-Indian Defense: Sämisch Variation","Nimzo Indian Samisch","Nimzo-Indian Defense","white","advanced","E24-E29","Accept doubled c-pawns and use the bishop pair plus a strong center to justify them.","Black blockades the c-pawns, attacks weak squares, and keeps the position closed for the knights.","Defending doubled pawns passively misses their value as space and file-opening tools.","White gets doubled c-pawns but also the bishop pair and central potential.","Use e4 and pawn breaks to open the position for the bishops.",["c3","c4","e4"],["nimzo","samisch","structure"]),
  course("queens-indian-defense","Queen's Indian Defense","Queen's Indian Defense",null,"black","intermediate","E12-E19","Control e4 with ...b6 and ...Bb7, develop flexibly, and challenge the center without overcommitting.","White uses space and active development to prevent easy central equality.","Letting the b7 bishop stare into a locked chain without another source of pressure makes the setup passive.","The long diagonal and e4 control are central to Black's hypermodern plan.","Use ...c5 or ...d5 when it improves the b7 bishop and attacks White's center.",["b7","e4","c5"],["queens-indian","fianchetto","positional"]),
  course("queens-indian-petrosian","Queen's Indian Defense: Petrosian Variation","Queen's Indian Petrosian","Queen's Indian Defense","white","advanced","E12","Use a3 to restrict ...Bb4 and prepare central expansion while gaining long-term control.","Black pressures c4 and e4 before White converts the extra space into a stable edge.","Playing a3 as a waiting move instead of connecting it to e4 or queenside expansion wastes a tempo.","White limits Black's dark bishop while preserving a broad center.","Prepare e4 when the knight and queen can support the occupation.",["a3","e4","c4"],["queens-indian","petrosian","prophylaxis"]),
  course("grunfeld-defense","Grünfeld Defense","Grunfeld Defense",null,"black","intermediate","D80-D99","Allow White to build a center, then attack it with the g7 bishop, ...c5, and piece pressure.","White uses the broad center for space and may turn it into an attack if it remains stable.","A Grünfeld without pressure on d4 and c3 simply gives White a free center.","White's pawn mass faces Black's long-diagonal and c-file pressure.","Use ...c5 to attack d4 before White advances the center safely.",["g7","d4","c5"],["grunfeld","hypermodern","center"]),
  course("grunfeld-exchange","Grünfeld Defense: Exchange Variation","Grunfeld Exchange","Grunfeld Defense","both","advanced","D85-D89","White builds an e4-d4 center while Black attacks it immediately with pieces and ...c5.","Black targets d4 and c3, proving the center is a target rather than only a strength.","Pushing the center before development can make the pawns tactically vulnerable.","A broad white center meets pressure from g7, c5, and the c-file.","White advances only when it gains something concrete; Black seeks ...c5.",["d4","e4","c5"],["grunfeld","exchange","dynamic-center"]),
  course("grunfeld-russian","Grünfeld Defense: Russian Variation","Grunfeld Russian","Grunfeld Defense","white","advanced","D97-D99","Use Qb3 to reinforce central pressure and create immediate tactical questions before Black develops fully.","Black attacks the queen with development and tries to turn early queen activity into lost tempi.","Letting the queen become a target for every developing move can erase White's central advantage.","White keeps a strong center while the queen supports pressure on d5 and b7.","Use e4 and d5 with piece support rather than relying on queen pressure alone.",["b3","d5","e4"],["grunfeld","russian","queen-pressure"]),
  course("benoni-defense","Benoni Defense","Benoni Defense",null,"black","intermediate","A56-A79","Challenge d4 with ...c5, accept space concessions, and create dynamic queenside and dark-square counterplay.","White uses the d5 wedge to restrict Black and prepare e4-e5 or queenside expansion.","Defending d6 with every piece instead of creating activity leads to a cramped position.","The d5 wedge gives White room while Black gains asymmetrical files and targets.","Use ...b5 or pressure on the center to attack White's space advantage.",["d5","d6","b5"],["benoni","asymmetrical","counterplay"]),
  course("modern-benoni","Modern Benoni","Modern Benoni","Benoni Defense","both","advanced","A60-A79","Accept a cramped center for dynamic ...b5 play, the g7 bishop, and active piece pressure.","White expands with e4-f4 and queenside space while targeting d6.","Passive defense of d6 misses the need for immediate counterplay.","White's d5 wedge and Black's d6 pawn create a fixed center with attacks on both wings.","Black prepares ...b5 while White often seeks e5; timing decides the initiative.",["d5","d6","b5"],["modern-benoni","dynamic","breaks"]),
  course("benko-gambit","Benko Gambit","Benko Gambit","Benoni Defense","black","advanced","A57-A59","Sacrifice a queenside pawn to open files, activate the g7 bishop, and create long-term pressure.","White tries to consolidate the extra pawn and exchange Black's active pieces.","Expecting immediate material recovery misunderstands the positional nature of the compensation.","Black gives a queenside pawn for persistent pressure against a2, b2, and the open files.","Use rooks and the g7 bishop to keep queenside pressure before White consolidates.",["a2","b2","b7"],["benko","gambit","queenside-pressure"]),
  course("bogo-indian-defense","Bogo-Indian Defense","Bogo-Indian Defense",null,"black","intermediate","E11","Use ...Bb4+ to force an early structural or piece-placement decision, then contest the center.","White decides whether to block, trade bishops, or accept small structural concessions.","Giving up the bishop without gaining development or structural value wastes the early check.","The check changes White's normal queenside development and can shape the pawn structure.","Use ...d5 or ...c5 after the check has induced a favorable setup.",["b4","d5","c5"],["bogo-indian","check","positional"]),
  course("old-indian-defense","Old Indian Defense","Old Indian Defense",null,"black","beginner","A53-A55","Build a compact ...d6-e5 center, develop behind it, and seek ...f5 or ...d5 counterplay.","White uses extra space and easier development to restrict Black before the freeing break.","Accepting a cramped setup without a plan for the c8 bishop and queenside knight creates lasting passivity.","Black's d6-e5 chain is solid but restricts pieces if it never changes.","Prepare ...f5 or ...d5 only after enough development supports the break.",["d6","e5","f5"],["old-indian","closed-center","breaks"]),
  course("budapest-gambit","Budapest Gambit","Budapest Gambit",null,"black","intermediate","A51-A52","Use ...e5 to challenge the d4-c4 center immediately and gain development tempi.","White returns or holds the pawn only if development stays smooth and tactics are controlled.","Spending too many moves recovering the gambit pawn destroys Black's time-based compensation.","Black opens the e-file and activates pieces quickly for a temporary pawn deficit.","Use active piece play to pressure c4 and central squares while completing development.",["e5","g4","c4"],["budapest","gambit","development"]),
];
