import type { OpeningLessonProfile } from "./types";

const family = "sicilian-defenses" as const;
function course(key: string, title: string, canonicalQuery: string, canonicalFallback: string | null, sideFocus: OpeningLessonProfile["sideFocus"], difficulty: OpeningLessonProfile["difficulty"], ecoRange: string, strategicPlan: string, opponentPlan: string, commonMistake: string, structureIdea: string, thematicBreak: string, keySquares: string[], tags: string[]): OpeningLessonProfile {
  return { key, slug: key, title, family, sideFocus, difficulty, ecoRange, canonicalQuery, canonicalFallback: canonicalFallback ?? undefined, summary: `${title} is taught through its recurring plan and structure: ${strategicPlan} ${structureIdea}`, strategicPlan, opponentPlan, commonMistake, trapWarning: `Tactical warning for ${title}: ${commonMistake} Check forcing replies before committing.`, structureIdea, thematicBreak, keySquares, tags };
}

export const SICILIAN_DEFENSE_PROFILES: OpeningLessonProfile[] = [
  course("sicilian-defense","Sicilian Defense","Sicilian Defense",null,"black","beginner","B20-B99","Create asymmetry with ...c5, pressure d4, and use the half-open c-file for active counterplay.","White uses the development lead and often targets d5 or the kingside before Black's queenside play matures.","Playing ...c5 and then defending passively wastes the purpose of the opening.","Black's c-pawn often trades for White's d-pawn, creating an open c-file and asymmetric majorities.","Use ...d5 when tactics permit to challenge White's center and release the position.",["c5","d4","d5"],["sicilian","asymmetrical","counterplay"]),
  course("sicilian-najdorf","Sicilian Defense: Najdorf Variation","Sicilian Najdorf","Sicilian Defense","black","advanced","B90-B99","Use ...a6 to control b5, keep ...e5/...e6 flexible, and choose counterplay according to White's setup.","White tries to exploit the development lead with kingside activity or a grip on d5.","Automatic queenside pawn pushes are dangerous while the king and center remain unsettled.","The Najdorf keeps a flexible central structure while both sides often attack on opposite wings.","Choose ...e5 for space or ...e6 for flexibility only after checking d5.",["a6","d5","e5"],["sicilian","najdorf","counterplay"]),
  course("sicilian-dragon","Sicilian Defense: Dragon Variation","Sicilian Dragon","Sicilian Defense","black","advanced","B70-B79","Fianchetto the dark bishop, pressure the long diagonal, and race for queenside counterplay.","White often castles long and attacks with h- and g-pawns while trying to exchange the g7 bishop.","Slow moves lose races in opposite-side castling positions where forcing play matters.","The g7 bishop and c-file give Black dynamic pressure against White's queenside and center.","Use ...d5 when available or ...b5 to accelerate counterplay against a long-castled king.",["g7","c3","d5"],["sicilian","dragon","opposite-castling"]),
  course("accelerated-dragon","Sicilian Defense: Accelerated Dragon","Accelerated Dragon","Sicilian Defense","black","intermediate","B34-B39","Fianchetto quickly while keeping the d-pawn free for an early ...d5 break.","White can establish a Maroczy Bind with c4 to restrict ...d5 and squeeze Black's activity.","Forcing ...d5 when White controls it strongly can leave isolated pawns and weak squares.","The key question is whether Black achieves ...d5 before White stabilizes c4-e4.","Prepare ...d5 with development and tactical support instead of treating it as automatic.",["d5","c4","e4"],["sicilian","fianchetto","breaks"]),
  course("sicilian-classical","Sicilian Defense: Classical Variation","Sicilian Classical","Sicilian Defense","black","intermediate","B56-B69","Develop ...Nc6 and ...Nf6 naturally, keep central options open, and pressure d4.","White uses Bg5, f4, or long castling to exploit extra space and development.","Trading the wrong minor piece can leave a permanent d5 outpost with no counterplay.","The structure keeps central pawns flexible while d5 becomes a major strategic landmark.","Time ...d5 or ...e5 before White's attack becomes forcing.",["d5","d4","c6"],["sicilian","classical","development"]),
  course("sicilian-scheveningen","Sicilian Defense: Scheveningen Variation","Sicilian Scheveningen","Sicilian Defense","black","advanced","B80-B89","Use the compact e6-d6 center, then counter with ...b5 or ...d5 while absorbing kingside space.","White often expands with f4-g4 and attacks before Black's counterplay arrives.","Remaining compressed without a freeing break turns flexibility into passivity.","Black's e6-d6 small center supports pieces but concedes space.","Prepare ...d5 as the ideal central liberation, with ...b5 as queenside counterplay.",["e6","d6","d5"],["sicilian","scheveningen","flexible-center"]),
  course("sicilian-sveshnikov","Sicilian Defense: Sveshnikov Variation","Sicilian Sveshnikov","Sicilian Defense","black","advanced","B33","Accept a d5 weakness for active play, central space with ...e5, and dynamic queenside breaks.","White occupies d5, targets d6, and tries to limit Black's active bishops.","Defending d5 passively misses the opening's dynamic compensation.","The ...e5 advance creates a d5 hole but gains space and drives the f3 knight.","Use ...f5 or ...b5 to create activity before White stabilizes d5.",["d5","e5","d6"],["sicilian","sveshnikov","dynamic"]),
  course("sicilian-kan","Sicilian Defense: Kan Variation","Sicilian Kan","Sicilian Defense","black","intermediate","B41-B43","Use ...e6 and ...a6 for flexibility, delaying commitments until White shows the setup.","White can build space with c4 or exploit Black's slower development.","Flexibility becomes passivity if Black never chooses ...b5 or ...d5.","The Kan keeps the c8 bishop and b8 knight flexible while controlling d5.","Expand with ...b5 or strike with ...d5 when development supports it.",["a6","b5","d5"],["sicilian","kan","flexible"]),
  course("sicilian-taimanov","Sicilian Defense: Taimanov Variation","Sicilian Taimanov","Sicilian Defense","black","intermediate","B46-B49","Develop ...Nc6 and ...e6 while keeping queen and bishop placement flexible.","White uses the development lead to pressure d5 and build Be3/Qd2 setups.","Early queen moves can become tactical targets on the c-file or dark squares.","Black keeps a flexible center with active pressure on d4.","Use ...d5 as the clean central equalizer when tactics permit.",["c6","d5","d4"],["sicilian","taimanov","flexible"]),
  course("sicilian-alapin","Sicilian Defense: Alapin Variation","Sicilian Alapin","Sicilian Defense","both","beginner","B22","White supports d4 with c3 to build a classical center; Black attacks it immediately.","Black uses ...d5 or ...Nf6 rather than relying on a typical open-Sicilian c-file battle.","White should not defend e4 passively after spending a tempo on c3.","The c3-d4 setup creates a broad center and reduces normal Sicilian asymmetry.","Challenge the center early; ...d5 is the most direct thematic response.",["c3","d4","d5"],["sicilian","alapin","center"]),
  course("closed-sicilian","Closed Sicilian","Closed Sicilian","Sicilian Defense","white","intermediate","B23-B26","Keep the center closed, build a kingside attack with f4, and use the g2 bishop.","Black expands on the queenside and challenges with ...b5, ...e6, and central breaks.","Pushing f5 or g4 before pieces are ready can create holes without an attack.","White's e4-f4 setup meets Black's c5 queenside space, producing opposite-wing plans.","Prepare f5 only after the king and minor pieces support the expansion.",["f4","f5","c5"],["sicilian","closed","kingside"]),
  course("smith-morra-gambit","Smith-Morra Gambit","Smith-Morra Gambit","Sicilian Defense","white","intermediate","B21","Sacrifice the c-pawn for rapid development, open central files, and pressure on d6.","Black consolidates the extra pawn, exchanges attackers, and neutralizes White's lead in development.","Trying to recover the c-pawn wastes the activity that justifies the gambit.","White trades a wing pawn for open c- and d-files and fast piece coordination.","Place rooks centrally and use e5 or pressure on d6 only when development justifies it.",["c1","d6","e5"],["sicilian","gambit","initiative"]),
  course("french-defense","French Defense","French Defense",null,"black","beginner","C00-C19","Attack e4 with ...d5, accept less space, and build counterplay around ...c5.","White uses e5 space to gain kingside room and restrict Black's pieces.","Leaving the light bishop imprisoned without an activation plan creates lasting passivity.","The e6-d5 chain challenges White's e4-e5 center and focuses play on d4.","Use ...c5 as the primary break and ...f6 when tactically justified.",["d4","c5","e5"],["french","pawn-chain","counterplay"]),
  course("french-advance","French Defense: Advance Variation","French Advance","French Defense","both","intermediate","C02","White gains space with e5; Black attacks the base with ...c5 and the head with ...f6.","Black undermines the center before White converts space into a kingside attack.","Defending every central pawn passively can let Black develop freely around the chain.","The e5-d4 chain points kingside while Black targets d4.","Black's ...c5 is fundamental; White often supports d4 with c3.",["e5","d4","c5"],["french","advance","space"]),
  course("french-winawer","French Defense: Winawer Variation","French Winawer","French Defense","both","advanced","C15-C19","Use ...Bb4 to pin Nc3 and accept structural imbalance for pressure on the center.","White uses space and the bishop pair, often accepting doubled c-pawns for activity.","Judging doubled c-pawns as automatically weak ignores their central and file-opening potential.","The Winawer creates an imbalanced queenside and sharp play around e5 and c3.","Black attacks with ...c5 and ...Ne7 while White builds kingside pressure.",["c3","e5","c5"],["french","winawer","imbalance"]),
  course("french-tarrasch","French Defense: Tarrasch Variation","French Tarrasch","French Defense","white","intermediate","C03-C09","Use Nd2 to support e4 without allowing the Winawer pin, then choose the right center.","Black gains freer piece play and still pressures d4 with ...c5.","Blocking the c1 bishop indefinitely makes White's flexible setup surprisingly passive.","White avoids doubled c-pawns but temporarily reduces queenside knight activity.","Prepare c3 and Ngf3, then meet ...c5 with active development.",["d2","d4","c5"],["french","tarrasch","flexible"]),
  course("caro-kann-defense","Caro-Kann Defense","Caro-Kann Defense",null,"black","beginner","B10-B19","Challenge e4 with ...c6-d5 while keeping the light bishop active outside the chain.","White uses space and development to test whether Black can complete development without passivity.","Spending too many tempi preserving the light bishop can delay king safety and central play.","Black's c6-d5 base is solid and usually concedes only modest space.","Use ...c5 or ...e5 later to challenge White's center after development.",["c6","d5","c5"],["caro-kann","solid","structure"]),
  course("caro-kann-advance","Caro-Kann Defense: Advance Variation","Caro-Kann Advance","Caro-Kann Defense","both","intermediate","B12","White gains space with e5; Black develops the light bishop and attacks the chain with ...c5.","Black undermines the center before White turns space into a kingside initiative.","Overprotecting e5 with slow moves lets Black develop comfortably around the pawn chain.","The e5-d4 chain gives White space but clear targets for Black's breaks.","Prepare ...c5 against d4 and sometimes ...f6 against e5.",["e5","d4","c5"],["caro-kann","advance","space"]),
  course("caro-kann-panov","Caro-Kann Defense: Panov Attack","Panov Attack Caro-Kann","Caro-Kann Defense","white","intermediate","B13-B14","Accept an isolated d-pawn for active pieces, open files, and central pressure.","Black blockades the isolated pawn, exchanges active pieces, and targets d4 later.","Defending the isolated pawn passively misses its value as an activity-generating asset.","The IQP gives White space and open lines but becomes a target after simplification.","Use d5 as a tactical or positional break when it releases pieces.",["d4","d5","e5"],["caro-kann","iqp","activity"]),
  course("pirc-defense","Pirc Defense","Pirc Defense",null,"black","intermediate","B07-B09","Allow a broad white center, fianchetto, then attack it with ...e5 or ...c5.","White uses extra space for central or kingside expansion before Black's counterattack.","Hypermodern play becomes passive if White's center is allowed to advance without a prepared break.","White's e4-d4 center gives space while Black's g7 bishop attacks from distance.","Choose ...e5 or ...c5 based on which break best attacks the pawn chain.",["d4","e4","e5"],["pirc","hypermodern","counterattack"]),
];
